version: "3.8"

# Entorno de desarrollo para NestJS, usar en caso no se pueda instalar Nodejs en local

services:
  app:
    image: nestjs/cli
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /opt/app/quiz-backend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always