version: '3.8'

# Run with: docker-compose -f .\docker-compose.mysql.yml up -d

services:
  db:
    image: mysql    
    hostname: quizapp
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_USER=quizusr
      - MYSQL_PASSWORD=nttl@nd315%aLz
      - MYSQL_DATABASE=quizappdb
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_USER=quizadm
      - MARIADB_ROOT_PASSWORD=a_nttl@nd_cL@&ap
    ports:
      - 3306:3306
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_db: